-- Seed idempotente de catálogo e ofertas DEMONSTRATIVAS. Preços não são reais.
USE churrasplan;
INSERT INTO categorias (nome,tipo) VALUES ('Carnes','carne') ON DUPLICATE KEY UPDATE tipo=VALUES(tipo);
INSERT INTO categorias (nome,tipo) VALUES ('Bebidas','bebida') ON DUPLICATE KEY UPDATE tipo=VALUES(tipo);
INSERT INTO categorias (nome,tipo) VALUES ('Extras','extra') ON DUPLICATE KEY UPDATE tipo=VALUES(tipo);
INSERT INTO categorias (nome,tipo) VALUES ('Acompanhamentos','acompanhamento') ON DUPLICATE KEY UPDATE tipo=VALUES(tipo);
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'picanha','Picanha','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'picanha-suina','Picanha suína','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'contra-file','Contra-filé','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'alcatra','Alcatra','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'fraldinha','Fraldinha','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'maminha','Maminha','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'acem','Acém','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'costela','Costela','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'costelinha-porco','Costelinha de porco','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'cupim','Cupim','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'linguica','Linguiça','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'lombo','Lombo','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'bisteca','Bisteca','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'frango','Frango','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'asinha-frango','Asinha de frango','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'coracao','Coração','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'queijo-coalho-churrasco','Queijo coalho','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'pao-alho-churrasco','Pão de alho','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'bife-ancho','Bife Ancho','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'bife-chorizo','Bife de Chorizo','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'prime-rib','Prime Rib','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'short-rib','Short Rib','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'file-mignon','Filé Mignon','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Carnes' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'carvao','Carvão','kg','saco',FALSE,NULL,3.0,'kg',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'agua','Água','litro','garrafa',FALSE,NULL,1.5,'litro',TRUE FROM categorias WHERE nome='Bebidas' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'refrigerante','Refrigerante','litro','garrafa',FALSE,NULL,2.0,'litro',TRUE FROM categorias WHERE nome='Bebidas' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'suco','Suco','litro','caixa',FALSE,NULL,1.0,'litro',TRUE FROM categorias WHERE nome='Bebidas' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'cerveja','Cerveja','litro','lata',FALSE,NULL,0.35,'litro',TRUE FROM categorias WHERE nome='Bebidas' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'gelo','Gelo','kg','saco',FALSE,NULL,5.0,'kg',TRUE FROM categorias WHERE nome='Bebidas' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'sal-grosso','Sal grosso','kg','pacote',FALSE,NULL,1.0,'kg',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'acendedor','Acendedor','unidade','unidade',FALSE,NULL,1.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'fosforo-isqueiro','Fósforo / isqueiro','unidade','unidade',FALSE,NULL,1.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'copos','Copos','unidade','pacote',FALSE,NULL,50.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'pratos','Pratos','unidade','pacote',FALSE,NULL,10.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'talheres','Talheres','unidade','pacote',FALSE,NULL,20.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'guardanapos','Guardanapos','unidade','pacote',FALSE,NULL,50.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'sacos-lixo','Sacos de lixo','unidade','pacote',FALSE,NULL,10.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'papel-toalha','Papel toalha','rolo','pacote',FALSE,NULL,2.0,'rolo',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'papel-aluminio','Papel alumínio','rolo','rolo',FALSE,NULL,1.0,'rolo',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'palitos','Palitos','unidade','caixa',FALSE,NULL,100.0,'unidade',TRUE FROM categorias WHERE nome='Extras' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'pao-de-alho','Pão de alho','unidade','pacote',FALSE,NULL,5.0,'unidade',TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'farofa','Farofa','kg','pacote',FALSE,NULL,0.5,'kg',TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'vinagrete','Vinagrete','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'queijo-coalho','Queijo coalho','kg','pacote',FALSE,NULL,0.5,'kg',TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'maionese','Maionese','kg','pote',FALSE,NULL,0.5,'kg',TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'salada','Salada','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'arroz','Arroz','kg','pacote',FALSE,NULL,1.0,'kg',TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'molhos','Molhos','litro','frasco',FALSE,NULL,0.25,'litro',TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;
INSERT INTO produtos (categoria_id,slug,nome,unidade_consumo,unidade_venda,venda_fracionada,incremento_venda,quantidade_embalagem,unidade_embalagem,ativo) SELECT id,'pao','Pão','kg','kg',TRUE,0.1,NULL,NULL,TRUE FROM categorias WHERE nome='Acompanhamentos' ON DUPLICATE KEY UPDATE nome=VALUES(nome), categoria_id=VALUES(categoria_id), unidade_consumo=VALUES(unidade_consumo), unidade_venda=VALUES(unidade_venda), venda_fracionada=VALUES(venda_fracionada), incremento_venda=VALUES(incremento_venda), quantidade_embalagem=VALUES(quantidade_embalagem), unidade_embalagem=VALUES(unidade_embalagem), ativo=TRUE;

INSERT INTO estabelecimentos (slug,nome,tipo,endereco,ativo) VALUES ('supermercado-exemplo-centro','Supermercado Exemplo Centro','supermercado','Rua Exemplo, 100',TRUE) ON DUPLICATE KEY UPDATE nome=VALUES(nome), endereco=VALUES(endereco), ativo=TRUE;
INSERT INTO estabelecimentos (slug,nome,tipo,endereco,ativo) VALUES ('acougue-exemplo-bairro','Açougue Exemplo Bairro','acougue','Av. Demonstração, 200',TRUE) ON DUPLICATE KEY UPDATE nome=VALUES(nome), endereco=VALUES(endereco), ativo=TRUE;
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,59.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='picanha' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,54.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='acougue-exemplo-bairro' WHERE p.slug='picanha' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,42.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='alcatra' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,39.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='acougue-exemplo-bairro' WHERE p.slug='alcatra' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,22.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='linguica' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,18.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='frango' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,18.00,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='carvao' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,3.50,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='agua' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,8.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='refrigerante' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,4.50,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='cerveja' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,14.00,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='gelo' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,6.50,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='sal-grosso' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,12.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='pao-de-alho' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,disponivel) SELECT p.id,e.id,9.90,'seed-demo-v2',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='farofa' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v2');

-- Cobertura DEMONSTRATIVA de preços para todo o catálogo padrão.
-- Estes valores existem apenas para desenvolvimento/testes locais; não são preços reais.
-- Em produção, carregue ofertas verificadas de parceiros/fontes autorizadas.
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,31.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='picanha-suina' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,44.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='contra-file' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,39.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='fraldinha' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,41.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='maminha' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,29.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='acem' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,32.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='costela' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,27.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='costelinha-porco' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,36.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='cupim' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,28.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='lombo' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,24.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='bisteca' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,17.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='asinha-frango' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,34.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='coracao' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,39.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='queijo-coalho-churrasco' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,22.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='pao-alho-churrasco' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,69.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='bife-ancho' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,64.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='bife-chorizo' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,74.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='prime-rib' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,58.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='short-rib' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,79.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='file-mignon' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,7.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='suco' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,9.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='acendedor' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,4.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='fosforo-isqueiro' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,8.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='copos' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,7.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='pratos' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,8.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='talheres' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,6.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='guardanapos' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,12.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='sacos-lixo' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,8.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='papel-toalha' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,11.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='papel-aluminio' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,4.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='palitos' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,18.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='vinagrete' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,19.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='queijo-coalho' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,9.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='maionese' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,16.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='salada' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,7.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='arroz' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,6.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='molhos' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
INSERT INTO precos (produto_id,estabelecimento_id,preco,fonte,origem,disponivel) SELECT p.id,e.id,14.90,'seed-demo-v3','seed_demo',TRUE FROM produtos p JOIN estabelecimentos e ON e.slug='supermercado-exemplo-centro' WHERE p.slug='pao' AND NOT EXISTS (SELECT 1 FROM precos px WHERE px.produto_id=p.id AND px.estabelecimento_id=e.id AND px.fonte='seed-demo-v3');
-- ============================================================
-- Fases 3-6: catálogo genérico e planos-base
-- ============================================================
UPDATE produtos
SET tipo_produto = 'generico'
WHERE produto_pai_id IS NULL AND (tipo_produto IS NULL OR tipo_produto <> 'comercial');

INSERT INTO planos_assinatura (slug, nome, publico_alvo, preco_mensal, recursos, ativo)
VALUES (
    'gratuito', 'Gratuito', 'usuario', 0.00,
    JSON_OBJECT(
        'planejamento', TRUE,
        'historico', TRUE,
        'convites', TRUE,
        'onde_comprar', TRUE
    ), TRUE
)
ON DUPLICATE KEY UPDATE
    nome = VALUES(nome), publico_alvo = VALUES(publico_alvo),
    preco_mensal = VALUES(preco_mensal), recursos = VALUES(recursos), ativo = TRUE;

INSERT INTO planos_assinatura (slug, nome, publico_alvo, preco_mensal, recursos, ativo)
VALUES (
    'parceiro', 'Parceiro', 'parceiro', 0.00,
    JSON_OBJECT(
        'painel_estabelecimento', TRUE,
        'produtos_comerciais', TRUE,
        'ofertas', TRUE
    ), TRUE
)
ON DUPLICATE KEY UPDATE
    nome = VALUES(nome), publico_alvo = VALUES(publico_alvo),
    preco_mensal = VALUES(preco_mensal), recursos = VALUES(recursos), ativo = TRUE;

-- Os preços acima são apenas dados demonstrativos. Para produção, cadastre
-- SKUs comerciais e ofertas verificadas pela área de parceiros/API.
